### ISSUE TITLE
Backend para recoger los formularios de la web

### ISSUE THREAD

**Issue by alo** [AlmeriaJS/AlmeriaJS#9]
Por ahora propongo mandar mail con los dos formularios que tendremos. 
- Propuesta de charla 
- Pedir camiseta friki solidaria

**Comment by alo** [comment]
Por ahora podemos usar algún php que mande un correo, si alguien quiere hacer otra propuesta, estamos escantados! ¿Algún proveedor de servicios serverless?

**Comment by Jhonsensf** [comment]
Podemos hacer una función serverless con Firebase Functions que se encargue de enviar el Mail. 

Además en un futuro nos puede valer si queremos almacenar algo en BBDD o cosas por el estilo. 

Me puedo encargar yo de esto.

**Comment by alo** [comment]
Perdón, estoy empanado, enlace a Google forms y listo... creamos el form y listo... cierro esto
